/*
**
** The C code is generated by [ATS/Postiats-0-2-11]
** The starting compilation time is: 2016-10-11: 13h:19m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1943(line=68, offs=1) -- 1992(line=70, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1749(line=57, offs=1) -- 1798(line=59, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 15396(line=856, offs=1) -- 15433(line=857, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1943(line=68, offs=1) -- 1992(line=70, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tysum_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_neq_ptr0_ptr0)
ATSdyncst_mac(atspre_neg_bool0)
ATSdyncst_mac(atspre_eq_ptr0_ptr0)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 194(line=14, offs=1) -- 229(line=14, offs=36)
*/
ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__point) ;
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSstatic()
atstkind_type(atstype_ptrk)
addr_of_0__0(atstkind_type(atstype_ptrk)) ;
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atsvoid_t0ype
link_1__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstkind_type(atstype_ptrk)
repr_2__2(atstkind_type(atstype_ptrk)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__fresh__3(atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__get_desc__4(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__set_desc__5(atstkind_type(atstype_ptrk), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__union__6(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__is_equiv__7(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__is_repr__8(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 245(line=16, offs=15) -- 294(line=17, offs=21)
*/
/*
local: 
global: addr_of_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_type(atstype_ptrk)
addr_of_0__0(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 245(line=16, offs=15) -- 294(line=17, offs=21)
*/
ATSINSflab(__patsflab_addr_of_0):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 275(line=17, offs=2) -- 294(line=17, offs=21)
*/
ATSINSmove(tmpret0, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), arg0)) ;
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [addr_of_0__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 360(line=19, offs=15) -- 411(line=20, offs=14)
*/
/*
local: 
global: link_1$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
link_1__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret1) ;
ATStmpdec(tmp2, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 360(line=19, offs=15) -- 411(line=20, offs=14)
*/
ATSINSflab(__patsflab_link_1):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 405(line=20, offs=8) -- 411(line=20, offs=14)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp2, postiats_tysum_0) ;
// #if(1)
ATSINSstore_con1_tag(tmp2, 0) ;
// #endif
ATSINSstore_con1_ofs(tmp2, postiats_tysum_0, atslab__0, arg1) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 399(line=20, offs=2) -- 411(line=20, offs=14)
*/
ATSINSstore(ATSderef(arg0, atstype_boxed), tmp2) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 399(line=20, offs=2) -- 411(line=20, offs=14)
*/
ATSINSmove_void(tmpret1, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [link_1__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 427(line=22, offs=15) -- 608(line=31, offs=6)
*/
/*
local: 
global: repr_2$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_type(atstype_ptrk)
repr_2__2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstype_boxed) ;
ATStmpdec(tmp5, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp6, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp7) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp10, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 427(line=22, offs=15) -- 608(line=31, offs=6)
*/
ATSINSflab(__patsflab_repr_2):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 464(line=23, offs=8) -- 466(line=23, offs=10)
*/
ATSINSmove(tmp4, ATSderef(arg0, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 458(line=23, offs=2) -- 608(line=31, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 474(line=24, offs=4) -- 480(line=24, offs=10)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 464(line=23, offs=8) -- 466(line=23, offs=10)
*/
ATSifnthen(ATSCKpat_con1(tmp4, 1)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 480(line=24, offs=10) -- 480(line=24, offs=10)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 484(line=24, offs=14) -- 485(line=24, offs=15)
*/
ATSINSmove(tmpret3, arg0) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 489(line=25, offs=4) -- 496(line=25, offs=11)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 464(line=23, offs=8) -- 466(line=23, offs=10)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(tmp4, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 496(line=25, offs=11) -- 496(line=25, offs=11)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 494(line=25, offs=9) -- 496(line=25, offs=11)
*/
ATSINSmove(tmp5, ATSSELcon(tmp4, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 503(line=26, offs=3) -- 608(line=31, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 521(line=27, offs=14) -- 528(line=27, offs=21)
*/
ATSINSmove(tmp6, PMVtmpltvar(repr$4201(0)<S2Evar(a(8490))>)(tmp5)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 544(line=28, offs=15) -- 555(line=28, offs=26)
*/
ATSINSmove(tmp9, PMVtmpltvar(addr_of$4196(0)<S2Evar(a(8490))>)(tmp6)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 559(line=28, offs=30) -- 569(line=28, offs=40)
*/
ATSINSmove(tmp10, PMVtmpltvar(addr_of$4196(0)<S2Evar(a(8490))>)(tmp5)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 544(line=28, offs=15) -- 569(line=28, offs=40)
*/
ATSINSmove(tmp8, atspre_neq_ptr0_ptr0(tmp9, tmp10)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 541(line=28, offs=12) -- 588(line=28, offs=59)
*/
ATSif(
tmp8
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 575(line=28, offs=46) -- 588(line=28, offs=59)
*/
ATSINSmove_void(tmp7, PMVtmpltvar(link$4198(0)<S2Evar(a(8490))>)(arg0, tmp6)) ;

} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 588(line=28, offs=59) -- 588(line=28, offs=59)
*/
ATSINSmove_void(tmp7, ATSPMVempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 598(line=30, offs=4) -- 601(line=30, offs=7)
*/
ATSINSmove(tmpret3, tmp6) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 503(line=26, offs=3) -- 608(line=31, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [repr_2__2] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 654(line=36, offs=21) -- 707(line=37, offs=44)
*/
/*
local: 
global: fresh$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8493)
tmparg = S2Evar(a(8493))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__fresh__3(atstyvar_type(a) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstype_boxed) ;
ATStmpdec(tmp13, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp14, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 648(line=36, offs=15) -- 707(line=37, offs=44)
*/
ATSINSflab(__patsflab_fresh):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 682(line=37, offs=19) -- 692(line=37, offs=29)
*/
ATSINSmove(tmp13, PMVtmpltcst(ref<S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))>)(ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 694(line=37, offs=31) -- 705(line=37, offs=42)
*/
ATSINSmove(tmp14, PMVtmpltcst(ref<S2Evar(a(8493))>)(arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 676(line=37, offs=13) -- 706(line=37, offs=43)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp12, postiats_tysum_1) ;
// #if(1)
ATSINSstore_con1_tag(tmp12, 1) ;
// #endif
ATSINSstore_con1_ofs(tmp12, postiats_tysum_1, atslab__0, tmp13) ;
ATSINSstore_con1_ofs(tmp12, postiats_tysum_1, atslab__1, tmp14) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 665(line=37, offs=2) -- 707(line=37, offs=44)
*/
ATSINSmove(tmpret11, PMVtmpltcst(ref<S2Eapp(S2Ecst(pt); S2Evar(a(8493)))>)(tmp12)) ;

ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__fresh__3] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 732(line=39, offs=24) -- 868(line=45, offs=32)
*/
/*
local: 
global: get_desc$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8494)
tmparg = S2Evar(a(8494))
tmpsub = None()
*/
atstyvar_type(a)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__get_desc__4(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstyvar_type(a)) ;
ATStmpdec(tmp16, atstype_boxed) ;
ATStmpdec(tmp18, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp19, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20, atstype_boxed) ;
ATStmpdec(tmp22, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp23, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp24, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 723(line=39, offs=15) -- 868(line=45, offs=32)
*/
ATSINSflab(__patsflab_get_desc):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 746(line=40, offs=8) -- 748(line=40, offs=10)
*/
ATSINSmove(tmp16, ATSderef(arg0, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 740(line=40, offs=2) -- 868(line=45, offs=32)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 756(line=41, offs=4) -- 770(line=41, offs=18)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 746(line=40, offs=8) -- 748(line=40, offs=10)
*/
ATSifnthen(ATSCKpat_con1(tmp16, 1)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 770(line=41, offs=18) -- 770(line=41, offs=18)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 765(line=41, offs=13) -- 769(line=41, offs=17)
*/
ATSINSmove(tmp18, ATSSELcon(tmp16, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 774(line=41, offs=22) -- 779(line=41, offs=27)
*/
ATSINSmove(tmpret15, ATSderef(tmp18, atstyvar_type(a))) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 783(line=42, offs=4) -- 789(line=42, offs=10)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 746(line=40, offs=8) -- 748(line=40, offs=10)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(tmp16, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 789(line=42, offs=10) -- 789(line=42, offs=10)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 788(line=42, offs=9) -- 789(line=42, offs=10)
*/
ATSINSmove(tmp19, ATSSELcon(tmp16, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 802(line=43, offs=9) -- 804(line=43, offs=11)
*/
ATSINSmove(tmp20, ATSderef(tmp19, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 796(line=43, offs=3) -- 868(line=45, offs=32)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 813(line=44, offs=5) -- 827(line=44, offs=19)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 802(line=43, offs=9) -- 804(line=43, offs=11)
*/
ATSifnthen(ATSCKpat_con1(tmp20, 1)) { ATSINSgoto(__atstmplab11) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 827(line=44, offs=19) -- 827(line=44, offs=19)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 822(line=44, offs=14) -- 826(line=44, offs=18)
*/
ATSINSmove(tmp22, ATSSELcon(tmp20, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 831(line=44, offs=23) -- 836(line=44, offs=28)
*/
ATSINSmove(tmpret15, ATSderef(tmp22, atstyvar_type(a))) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 841(line=45, offs=5) -- 847(line=45, offs=11)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 802(line=43, offs=9) -- 804(line=43, offs=11)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(tmp20, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 847(line=45, offs=11) -- 847(line=45, offs=11)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 846(line=45, offs=10) -- 847(line=45, offs=11)
*/
ATSINSmove(tmp23, ATSSELcon(tmp20, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 861(line=45, offs=25) -- 867(line=45, offs=31)
*/
ATSINSmove(tmp24, PMVtmpltvar(repr$4201(0)<S2Evar(a(8494))>)(tmp23)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 851(line=45, offs=15) -- 868(line=45, offs=32)
*/
ATSINSmove(tmpret15, PMVtmpltcst(get_desc<S2Evar(a(8494))>)(tmp24)) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__get_desc__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 893(line=47, offs=24) -- 1058(line=53, offs=38)
*/
/*
local: 
global: set_desc$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8499)
tmparg = S2Evar(a(8499))
tmpsub = None()
*/
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__set_desc__5(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret25) ;
ATStmpdec(tmp26, atstype_boxed) ;
ATStmpdec(tmp28, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp30, atstype_boxed) ;
ATStmpdec(tmp32, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp33, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp34, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 884(line=47, offs=15) -- 1058(line=53, offs=38)
*/
ATSINSflab(__patsflab_set_desc):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 913(line=48, offs=8) -- 915(line=48, offs=10)
*/
ATSINSmove(tmp26, ATSderef(arg0, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 907(line=48, offs=2) -- 1058(line=53, offs=38)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 923(line=49, offs=4) -- 937(line=49, offs=18)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 913(line=48, offs=8) -- 915(line=48, offs=10)
*/
ATSifnthen(ATSCKpat_con1(tmp26, 1)) { ATSINSgoto(__atstmplab15) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 937(line=49, offs=18) -- 937(line=49, offs=18)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 932(line=49, offs=13) -- 936(line=49, offs=17)
*/
ATSINSmove(tmp28, ATSSELcon(tmp26, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 941(line=49, offs=22) -- 954(line=49, offs=35)
*/
ATSINSstore(ATSderef(tmp28, atstyvar_type(a)), arg1) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 941(line=49, offs=22) -- 954(line=49, offs=35)
*/
ATSINSmove_void(tmpret25, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 958(line=50, offs=4) -- 964(line=50, offs=10)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 913(line=48, offs=8) -- 915(line=48, offs=10)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(tmp26, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 964(line=50, offs=10) -- 964(line=50, offs=10)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 963(line=50, offs=9) -- 964(line=50, offs=10)
*/
ATSINSmove(tmp29, ATSSELcon(tmp26, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 977(line=51, offs=9) -- 979(line=51, offs=11)
*/
ATSINSmove(tmp30, ATSderef(tmp29, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 971(line=51, offs=3) -- 1058(line=53, offs=38)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 988(line=52, offs=5) -- 1002(line=52, offs=19)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 977(line=51, offs=9) -- 979(line=51, offs=11)
*/
ATSifnthen(ATSCKpat_con1(tmp30, 1)) { ATSINSgoto(__atstmplab19) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1002(line=52, offs=19) -- 1002(line=52, offs=19)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 997(line=52, offs=14) -- 1001(line=52, offs=18)
*/
ATSINSmove(tmp32, ATSSELcon(tmp30, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1006(line=52, offs=23) -- 1019(line=52, offs=36)
*/
ATSINSstore(ATSderef(tmp32, atstyvar_type(a)), arg1) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1006(line=52, offs=23) -- 1019(line=52, offs=36)
*/
ATSINSmove_void(tmpret25, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1025(line=53, offs=5) -- 1031(line=53, offs=11)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 977(line=51, offs=9) -- 979(line=51, offs=11)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(tmp30, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1031(line=53, offs=11) -- 1031(line=53, offs=11)
*/
ATSINSlab(__atstmplab19):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1030(line=53, offs=10) -- 1031(line=53, offs=11)
*/
ATSINSmove(tmp33, ATSSELcon(tmp30, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1045(line=53, offs=25) -- 1051(line=53, offs=31)
*/
ATSINSmove(tmp34, PMVtmpltvar(repr$4201(0)<S2Evar(a(8499))>)(tmp33)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1035(line=53, offs=15) -- 1058(line=53, offs=38)
*/
ATSINSmove_void(tmpret25, PMVtmpltcst(set_desc<S2Evar(a(8499))>)(tmp34, arg1)) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret25) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__set_desc__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1080(line=55, offs=21) -- 1384(line=66, offs=4)
*/
/*
local: 
global: union$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8504)
tmparg = S2Evar(a(8504))
tmpsub = None()
*/
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__union__6(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret35) ;
ATStmpdec(tmp36, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp37, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40, atstype_boxed) ;
ATStmpdec(tmp41, atstype_boxed) ;
ATStmpdec(tmp42, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp43, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp44, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp47) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp49, atstyvar_type(a)) ;
// ATStmpdec_void(tmp50) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp52, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1074(line=55, offs=15) -- 1384(line=66, offs=4)
*/
ATSINSflab(__patsflab_union):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1094(line=55, offs=35) -- 1384(line=66, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1109(line=56, offs=11) -- 1116(line=56, offs=18)
*/
ATSINSmove(tmp36, PMVtmpltvar(repr$4201(0)<S2Evar(a(8504))>)(arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1128(line=57, offs=11) -- 1135(line=57, offs=18)
*/
ATSINSmove(tmp37, PMVtmpltvar(repr$4201(0)<S2Evar(a(8504))>)(arg1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1150(line=59, offs=10) -- 1167(line=59, offs=27)
*/
ATSINSmove(tmp39, PMVtmpltcst(is_equiv<S2Evar(a(8504))>)(tmp36, tmp37)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1145(line=59, offs=5) -- 1168(line=59, offs=28)
*/
ATSINSmove(tmp38, atspre_neg_bool0(tmp39)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1142(line=59, offs=2) -- 1380(line=65, offs=63)
*/
ATSif(
tmp38
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1185(line=61, offs=10) -- 1188(line=61, offs=13)
*/
ATSINSmove(tmp40, ATSderef(tmp36, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1190(line=61, offs=15) -- 1193(line=61, offs=18)
*/
ATSINSmove(tmp41, ATSderef(tmp37, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1178(line=61, offs=3) -- 1380(line=65, offs=63)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1203(line=62, offs=6) -- 1216(line=62, offs=19)
*/
ATSINSlab(__atstmplab20):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1185(line=61, offs=10) -- 1188(line=61, offs=13)
*/
ATSifnthen(ATSCKpat_con1(tmp40, 1)) { ATSINScaseof_fail("/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1178(line=61, offs=3) -- 1380(line=65, offs=63)") ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1218(line=62, offs=21) -- 1231(line=62, offs=34)
*/
ATSINSlab(__atstmplab21):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1190(line=61, offs=15) -- 1193(line=61, offs=18)
*/
ATSifnthen(ATSCKpat_con1(tmp41, 1)) { ATSINScaseof_fail("/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1178(line=61, offs=3) -- 1380(line=65, offs=63)") ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1231(line=62, offs=34) -- 1231(line=62, offs=34)
*/
ATSINSlab(__atstmplab22):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1209(line=62, offs=12) -- 1211(line=62, offs=14)
*/
ATSINSmove(tmp42, ATSSELcon(tmp40, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1213(line=62, offs=16) -- 1215(line=62, offs=18)
*/
ATSINSmove(tmp43, ATSSELcon(tmp40, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1224(line=62, offs=27) -- 1226(line=62, offs=29)
*/
ATSINSmove(tmp44, ATSSELcon(tmp41, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1228(line=62, offs=31) -- 1230(line=62, offs=33)
*/
ATSINSmove(tmp45, ATSSELcon(tmp41, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1243(line=63, offs=7) -- 1253(line=63, offs=17)
*/
ATSINSmove(tmp46, PMVtmpltcst(gte_g0int_int<S2Eextkind(atstype_int)>)(ATSderef(tmp42, atstkind_t0ype(atstype_int)), ATSderef(tmp44, atstkind_t0ype(atstype_int)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1240(line=63, offs=4) -- 1380(line=65, offs=63)
*/
ATSif(
tmp46
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1264(line=64, offs=10) -- 1277(line=64, offs=23)
*/
ATSINSmove_void(tmp47, PMVtmpltvar(link$4198(0)<S2Evar(a(8504))>)(tmp37, tmp36)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1286(line=64, offs=32) -- 1295(line=64, offs=41)
*/
ATSINSmove(tmp48, PMVtmpltcst(g0int_add<S2Eextkind(atstype_int)>)(ATSderef(tmp42, atstkind_t0ype(atstype_int)), ATSderef(tmp44, atstkind_t0ype(atstype_int)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1279(line=64, offs=25) -- 1295(line=64, offs=41)
*/
ATSINSstore(ATSderef(tmp42, atstkind_t0ype(atstype_int)), tmp48) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1304(line=64, offs=50) -- 1316(line=64, offs=62)
*/
ATSINSmove(tmp49, ATSfunclo_clo(arg2, (atstype_cloptr, atstyvar_type(a), atstyvar_type(a)), atstyvar_type(a))(arg2, ATSderef(tmp43, atstyvar_type(a)), ATSderef(tmp45, atstyvar_type(a)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1297(line=64, offs=43) -- 1316(line=64, offs=62)
*/
ATSINSstore(ATSderef(tmp43, atstyvar_type(a)), tmp49) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1297(line=64, offs=43) -- 1316(line=64, offs=62)
*/
ATSINSmove_void(tmpret35, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1327(line=65, offs=10) -- 1340(line=65, offs=23)
*/
ATSINSmove_void(tmp50, PMVtmpltvar(link$4198(0)<S2Evar(a(8504))>)(tmp36, tmp37)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1349(line=65, offs=32) -- 1358(line=65, offs=41)
*/
ATSINSmove(tmp51, PMVtmpltcst(g0int_add<S2Eextkind(atstype_int)>)(ATSderef(tmp42, atstkind_t0ype(atstype_int)), ATSderef(tmp44, atstkind_t0ype(atstype_int)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1342(line=65, offs=25) -- 1358(line=65, offs=41)
*/
ATSINSstore(ATSderef(tmp44, atstkind_t0ype(atstype_int)), tmp51) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1367(line=65, offs=50) -- 1379(line=65, offs=62)
*/
ATSINSmove(tmp52, ATSfunclo_clo(arg2, (atstype_cloptr, atstyvar_type(a), atstyvar_type(a)), atstyvar_type(a))(arg2, ATSderef(tmp43, atstyvar_type(a)), ATSderef(tmp45, atstyvar_type(a)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1360(line=65, offs=43) -- 1379(line=65, offs=62)
*/
ATSINSstore(ATSderef(tmp45, atstyvar_type(a)), tmp52) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1360(line=65, offs=43) -- 1379(line=65, offs=62)
*/
ATSINSmove_void(tmpret35, ATSPMVempty()) ;
} /* ATSendif */
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1380(line=65, offs=63) -- 1380(line=65, offs=63)
*/
ATSINSmove_void(tmpret35, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1094(line=55, offs=35) -- 1384(line=66, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret35) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__union__6] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1410(line=68, offs=24) -- 1460(line=69, offs=39)
*/
/*
local: 
global: is_equiv$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8507)
tmparg = S2Evar(a(8507))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__is_equiv__7(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret53, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp54, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp55, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp56, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp57, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1401(line=68, offs=15) -- 1460(line=69, offs=39)
*/
ATSINSflab(__patsflab_is_equiv):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1432(line=69, offs=11) -- 1439(line=69, offs=18)
*/
ATSINSmove(tmp55, PMVtmpltvar(repr$4201(0)<S2Evar(a(8507))>)(arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1423(line=69, offs=2) -- 1440(line=69, offs=19)
*/
ATSINSmove(tmp54, PMVtmpltvar(addr_of$4196(0)<S2Evar(a(8507))>)(tmp55)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1452(line=69, offs=31) -- 1459(line=69, offs=38)
*/
ATSINSmove(tmp57, PMVtmpltvar(repr$4201(0)<S2Evar(a(8507))>)(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1443(line=69, offs=22) -- 1460(line=69, offs=39)
*/
ATSINSmove(tmp56, PMVtmpltvar(addr_of$4196(0)<S2Evar(a(8507))>)(tmp57)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1423(line=69, offs=2) -- 1460(line=69, offs=39)
*/
ATSINSmove(tmpret53, atspre_eq_ptr0_ptr0(tmp54, tmp56)) ;

ATSfunbody_end()
ATSreturn(tmpret53) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__is_equiv__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1484(line=71, offs=23) -- 1542(line=74, offs=18)
*/
/*
local: 
global: is_repr$8$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8508)
tmparg = S2Evar(a(8508))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__is_repr__8(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret58, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp59, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1476(line=71, offs=15) -- 1542(line=74, offs=18)
*/
ATSINSflab(__patsflab_is_repr):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1498(line=72, offs=8) -- 1500(line=72, offs=10)
*/
ATSINSmove(tmp59, ATSderef(arg0, atstype_boxed)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1492(line=72, offs=2) -- 1542(line=74, offs=18)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1508(line=73, offs=4) -- 1514(line=73, offs=10)
*/
ATSINSlab(__atstmplab23):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1498(line=72, offs=8) -- 1500(line=72, offs=10)
*/
ATSifnthen(ATSCKpat_con1(tmp59, 1)) { ATSINSgoto(__atstmplab26) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1514(line=73, offs=10) -- 1514(line=73, offs=10)
*/
ATSINSlab(__atstmplab24):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1518(line=73, offs=14) -- 1523(line=73, offs=19)
*/
ATSINSmove(tmpret58, ATSPMVbool_false()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1528(line=74, offs=4) -- 1534(line=74, offs=10)
*/
ATSINSlab(__atstmplab25):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1498(line=72, offs=8) -- 1500(line=72, offs=10)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(tmp59, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1534(line=74, offs=10) -- 1534(line=74, offs=10)
*/
ATSINSlab(__atstmplab26):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-learn-lambda/lamcal-infer/unionfind.dats: 1538(line=74, offs=14) -- 1542(line=74, offs=18)
*/
ATSINSmove(tmpret58, ATSPMVbool_true()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret58) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_sats__is_repr__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_learn_055_lambda_057_lamcal_055_infer_057_unionfind_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
